/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InfluencersRouteImport } from './routes/influencers'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingProviderRouteImport } from './routes/onboarding.provider'
import { Route as OnboardingAdvertiserRouteImport } from './routes/onboarding.advertiser'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppProviderRouteImport } from './routes/app.provider'
import { Route as AppAdvertiserRouteImport } from './routes/app.advertiser'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppProviderIndexRouteImport } from './routes/app.provider.index'
import { Route as AppAdvertiserIndexRouteImport } from './routes/app.advertiser.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppProviderReviewsRouteImport } from './routes/app.provider.reviews'
import { Route as AppProviderRequestsRouteImport } from './routes/app.provider.requests'
import { Route as AppProviderProfileRouteImport } from './routes/app.provider.profile'
import { Route as AppProviderMessagesRouteImport } from './routes/app.provider.messages'
import { Route as AppProviderInventoryRouteImport } from './routes/app.provider.inventory'
import { Route as AppProviderFinancesRouteImport } from './routes/app.provider.finances'
import { Route as AppProviderBookingsRouteImport } from './routes/app.provider.bookings'
import { Route as AppAdvertiserReviewsRouteImport } from './routes/app.advertiser.reviews'
import { Route as AppAdvertiserProfileRouteImport } from './routes/app.advertiser.profile'
import { Route as AppAdvertiserMessagesRouteImport } from './routes/app.advertiser.messages'
import { Route as AppAdvertiserDiscoverRouteImport } from './routes/app.advertiser.discover'
import { Route as AppAdvertiserCampaignsRouteImport } from './routes/app.advertiser.campaigns'
import { Route as AppAdvertiserBookingsRouteImport } from './routes/app.advertiser.bookings'
import { Route as AppAdvertiserBillingRouteImport } from './routes/app.advertiser.billing'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminReportsRouteImport } from './routes/app.admin.reports'
import { Route as AppAdminProvidersRouteImport } from './routes/app.admin.providers'
import { Route as AppAdminLookupsRouteImport } from './routes/app.admin.lookups'
import { Route as AppAdminFinanceRouteImport } from './routes/app.admin.finance'
import { Route as AppAdminCampaignsRouteImport } from './routes/app.admin.campaigns'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppAdvertiserDiscoverIdRouteImport } from './routes/app.advertiser.discover.$id'

const InfluencersRoute = InfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProviderRoute = OnboardingProviderRouteImport.update({
  id: '/onboarding/provider',
  path: '/onboarding/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAdvertiserRoute = OnboardingAdvertiserRouteImport.update({
  id: '/onboarding/advertiser',
  path: '/onboarding/advertiser',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProviderRoute = AppProviderRouteImport.update({
  id: '/app/provider',
  path: '/app/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdvertiserRoute = AppAdvertiserRouteImport.update({
  id: '/app/advertiser',
  path: '/app/advertiser',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProviderIndexRoute = AppProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProviderRoute,
} as any)
const AppAdvertiserIndexRoute = AppAdvertiserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdvertiserRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppProviderReviewsRoute = AppProviderReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppProviderRoute,
} as any)
const AppProviderRequestsRoute = AppProviderRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppProviderRoute,
} as any)
const AppProviderProfileRoute = AppProviderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppProviderRoute,
} as any)
const AppProviderMessagesRoute = AppProviderMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppProviderRoute,
} as any)
const AppProviderInventoryRoute = AppProviderInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppProviderRoute,
} as any)
const AppProviderFinancesRoute = AppProviderFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppProviderRoute,
} as any)
const AppProviderBookingsRoute = AppProviderBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppProviderRoute,
} as any)
const AppAdvertiserReviewsRoute = AppAdvertiserReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppAdvertiserRoute,
} as any)
const AppAdvertiserProfileRoute = AppAdvertiserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAdvertiserRoute,
} as any)
const AppAdvertiserMessagesRoute = AppAdvertiserMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppAdvertiserRoute,
} as any)
const AppAdvertiserDiscoverRoute = AppAdvertiserDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppAdvertiserRoute,
} as any)
const AppAdvertiserCampaignsRoute = AppAdvertiserCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppAdvertiserRoute,
} as any)
const AppAdvertiserBookingsRoute = AppAdvertiserBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppAdvertiserRoute,
} as any)
const AppAdvertiserBillingRoute = AppAdvertiserBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppAdvertiserRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProvidersRoute = AppAdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLookupsRoute = AppAdminLookupsRouteImport.update({
  id: '/lookups',
  path: '/lookups',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFinanceRoute = AppAdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCampaignsRoute = AppAdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdvertiserDiscoverIdRoute = AppAdvertiserDiscoverIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdvertiserDiscoverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/influencers': typeof InfluencersRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/advertiser': typeof AppAdvertiserRouteWithChildren
  '/app/provider': typeof AppProviderRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/advertiser': typeof OnboardingAdvertiserRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/finance': typeof AppAdminFinanceRoute
  '/app/admin/lookups': typeof AppAdminLookupsRoute
  '/app/admin/providers': typeof AppAdminProvidersRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/advertiser/billing': typeof AppAdvertiserBillingRoute
  '/app/advertiser/bookings': typeof AppAdvertiserBookingsRoute
  '/app/advertiser/campaigns': typeof AppAdvertiserCampaignsRoute
  '/app/advertiser/discover': typeof AppAdvertiserDiscoverRouteWithChildren
  '/app/advertiser/messages': typeof AppAdvertiserMessagesRoute
  '/app/advertiser/profile': typeof AppAdvertiserProfileRoute
  '/app/advertiser/reviews': typeof AppAdvertiserReviewsRoute
  '/app/provider/bookings': typeof AppProviderBookingsRoute
  '/app/provider/finances': typeof AppProviderFinancesRoute
  '/app/provider/inventory': typeof AppProviderInventoryRoute
  '/app/provider/messages': typeof AppProviderMessagesRoute
  '/app/provider/profile': typeof AppProviderProfileRoute
  '/app/provider/requests': typeof AppProviderRequestsRoute
  '/app/provider/reviews': typeof AppProviderReviewsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/advertiser/': typeof AppAdvertiserIndexRoute
  '/app/provider/': typeof AppProviderIndexRoute
  '/app/advertiser/discover/$id': typeof AppAdvertiserDiscoverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/influencers': typeof InfluencersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/advertiser': typeof OnboardingAdvertiserRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/finance': typeof AppAdminFinanceRoute
  '/app/admin/lookups': typeof AppAdminLookupsRoute
  '/app/admin/providers': typeof AppAdminProvidersRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/advertiser/billing': typeof AppAdvertiserBillingRoute
  '/app/advertiser/bookings': typeof AppAdvertiserBookingsRoute
  '/app/advertiser/campaigns': typeof AppAdvertiserCampaignsRoute
  '/app/advertiser/discover': typeof AppAdvertiserDiscoverRouteWithChildren
  '/app/advertiser/messages': typeof AppAdvertiserMessagesRoute
  '/app/advertiser/profile': typeof AppAdvertiserProfileRoute
  '/app/advertiser/reviews': typeof AppAdvertiserReviewsRoute
  '/app/provider/bookings': typeof AppProviderBookingsRoute
  '/app/provider/finances': typeof AppProviderFinancesRoute
  '/app/provider/inventory': typeof AppProviderInventoryRoute
  '/app/provider/messages': typeof AppProviderMessagesRoute
  '/app/provider/profile': typeof AppProviderProfileRoute
  '/app/provider/requests': typeof AppProviderRequestsRoute
  '/app/provider/reviews': typeof AppProviderReviewsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/advertiser': typeof AppAdvertiserIndexRoute
  '/app/provider': typeof AppProviderIndexRoute
  '/app/advertiser/discover/$id': typeof AppAdvertiserDiscoverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/influencers': typeof InfluencersRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/advertiser': typeof AppAdvertiserRouteWithChildren
  '/app/provider': typeof AppProviderRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/advertiser': typeof OnboardingAdvertiserRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/finance': typeof AppAdminFinanceRoute
  '/app/admin/lookups': typeof AppAdminLookupsRoute
  '/app/admin/providers': typeof AppAdminProvidersRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/advertiser/billing': typeof AppAdvertiserBillingRoute
  '/app/advertiser/bookings': typeof AppAdvertiserBookingsRoute
  '/app/advertiser/campaigns': typeof AppAdvertiserCampaignsRoute
  '/app/advertiser/discover': typeof AppAdvertiserDiscoverRouteWithChildren
  '/app/advertiser/messages': typeof AppAdvertiserMessagesRoute
  '/app/advertiser/profile': typeof AppAdvertiserProfileRoute
  '/app/advertiser/reviews': typeof AppAdvertiserReviewsRoute
  '/app/provider/bookings': typeof AppProviderBookingsRoute
  '/app/provider/finances': typeof AppProviderFinancesRoute
  '/app/provider/inventory': typeof AppProviderInventoryRoute
  '/app/provider/messages': typeof AppProviderMessagesRoute
  '/app/provider/profile': typeof AppProviderProfileRoute
  '/app/provider/requests': typeof AppProviderRequestsRoute
  '/app/provider/reviews': typeof AppProviderReviewsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/advertiser/': typeof AppAdvertiserIndexRoute
  '/app/provider/': typeof AppProviderIndexRoute
  '/app/advertiser/discover/$id': typeof AppAdvertiserDiscoverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/faq'
    | '/how-it-works'
    | '/influencers'
    | '/app/admin'
    | '/app/advertiser'
    | '/app/provider'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/onboarding/advertiser'
    | '/onboarding/provider'
    | '/app/admin/audit'
    | '/app/admin/campaigns'
    | '/app/admin/finance'
    | '/app/admin/lookups'
    | '/app/admin/providers'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/advertiser/billing'
    | '/app/advertiser/bookings'
    | '/app/advertiser/campaigns'
    | '/app/advertiser/discover'
    | '/app/advertiser/messages'
    | '/app/advertiser/profile'
    | '/app/advertiser/reviews'
    | '/app/provider/bookings'
    | '/app/provider/finances'
    | '/app/provider/inventory'
    | '/app/provider/messages'
    | '/app/provider/profile'
    | '/app/provider/requests'
    | '/app/provider/reviews'
    | '/app/admin/'
    | '/app/advertiser/'
    | '/app/provider/'
    | '/app/advertiser/discover/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/faq'
    | '/how-it-works'
    | '/influencers'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/onboarding/advertiser'
    | '/onboarding/provider'
    | '/app/admin/audit'
    | '/app/admin/campaigns'
    | '/app/admin/finance'
    | '/app/admin/lookups'
    | '/app/admin/providers'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/advertiser/billing'
    | '/app/advertiser/bookings'
    | '/app/advertiser/campaigns'
    | '/app/advertiser/discover'
    | '/app/advertiser/messages'
    | '/app/advertiser/profile'
    | '/app/advertiser/reviews'
    | '/app/provider/bookings'
    | '/app/provider/finances'
    | '/app/provider/inventory'
    | '/app/provider/messages'
    | '/app/provider/profile'
    | '/app/provider/requests'
    | '/app/provider/reviews'
    | '/app/admin'
    | '/app/advertiser'
    | '/app/provider'
    | '/app/advertiser/discover/$id'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/faq'
    | '/how-it-works'
    | '/influencers'
    | '/app/admin'
    | '/app/advertiser'
    | '/app/provider'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/onboarding/advertiser'
    | '/onboarding/provider'
    | '/app/admin/audit'
    | '/app/admin/campaigns'
    | '/app/admin/finance'
    | '/app/admin/lookups'
    | '/app/admin/providers'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/advertiser/billing'
    | '/app/advertiser/bookings'
    | '/app/advertiser/campaigns'
    | '/app/advertiser/discover'
    | '/app/advertiser/messages'
    | '/app/advertiser/profile'
    | '/app/advertiser/reviews'
    | '/app/provider/bookings'
    | '/app/provider/finances'
    | '/app/provider/inventory'
    | '/app/provider/messages'
    | '/app/provider/profile'
    | '/app/provider/requests'
    | '/app/provider/reviews'
    | '/app/admin/'
    | '/app/advertiser/'
    | '/app/provider/'
    | '/app/advertiser/discover/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InfluencersRoute: typeof InfluencersRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAdvertiserRoute: typeof AppAdvertiserRouteWithChildren
  AppProviderRoute: typeof AppProviderRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OnboardingAdvertiserRoute: typeof OnboardingAdvertiserRoute
  OnboardingProviderRoute: typeof OnboardingProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/influencers': {
      id: '/influencers'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof InfluencersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/provider': {
      id: '/onboarding/provider'
      path: '/onboarding/provider'
      fullPath: '/onboarding/provider'
      preLoaderRoute: typeof OnboardingProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/advertiser': {
      id: '/onboarding/advertiser'
      path: '/onboarding/advertiser'
      fullPath: '/onboarding/advertiser'
      preLoaderRoute: typeof OnboardingAdvertiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/provider': {
      id: '/app/provider'
      path: '/app/provider'
      fullPath: '/app/provider'
      preLoaderRoute: typeof AppProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/advertiser': {
      id: '/app/advertiser'
      path: '/app/advertiser'
      fullPath: '/app/advertiser'
      preLoaderRoute: typeof AppAdvertiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/provider/': {
      id: '/app/provider/'
      path: '/'
      fullPath: '/app/provider/'
      preLoaderRoute: typeof AppProviderIndexRouteImport
      parentRoute: typeof AppProviderRoute
    }
    '/app/advertiser/': {
      id: '/app/advertiser/'
      path: '/'
      fullPath: '/app/advertiser/'
      preLoaderRoute: typeof AppAdvertiserIndexRouteImport
      parentRoute: typeof AppAdvertiserRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/provider/reviews': {
      id: '/app/provider/reviews'
      path: '/reviews'
      fullPath: '/app/provider/reviews'
      preLoaderRoute: typeof AppProviderReviewsRouteImport
      parentRoute: typeof AppProviderRoute
    }
    '/app/provider/requests': {
      id: '/app/provider/requests'
      path: '/requests'
      fullPath: '/app/provider/requests'
      preLoaderRoute: typeof AppProviderRequestsRouteImport
      parentRoute: typeof AppProviderRoute
    }
    '/app/provider/profile': {
      id: '/app/provider/profile'
      path: '/profile'
      fullPath: '/app/provider/profile'
      preLoaderRoute: typeof AppProviderProfileRouteImport
      parentRoute: typeof AppProviderRoute
    }
    '/app/provider/messages': {
      id: '/app/provider/messages'
      path: '/messages'
      fullPath: '/app/provider/messages'
      preLoaderRoute: typeof AppProviderMessagesRouteImport
      parentRoute: typeof AppProviderRoute
    }
    '/app/provider/inventory': {
      id: '/app/provider/inventory'
      path: '/inventory'
      fullPath: '/app/provider/inventory'
      preLoaderRoute: typeof AppProviderInventoryRouteImport
      parentRoute: typeof AppProviderRoute
    }
    '/app/provider/finances': {
      id: '/app/provider/finances'
      path: '/finances'
      fullPath: '/app/provider/finances'
      preLoaderRoute: typeof AppProviderFinancesRouteImport
      parentRoute: typeof AppProviderRoute
    }
    '/app/provider/bookings': {
      id: '/app/provider/bookings'
      path: '/bookings'
      fullPath: '/app/provider/bookings'
      preLoaderRoute: typeof AppProviderBookingsRouteImport
      parentRoute: typeof AppProviderRoute
    }
    '/app/advertiser/reviews': {
      id: '/app/advertiser/reviews'
      path: '/reviews'
      fullPath: '/app/advertiser/reviews'
      preLoaderRoute: typeof AppAdvertiserReviewsRouteImport
      parentRoute: typeof AppAdvertiserRoute
    }
    '/app/advertiser/profile': {
      id: '/app/advertiser/profile'
      path: '/profile'
      fullPath: '/app/advertiser/profile'
      preLoaderRoute: typeof AppAdvertiserProfileRouteImport
      parentRoute: typeof AppAdvertiserRoute
    }
    '/app/advertiser/messages': {
      id: '/app/advertiser/messages'
      path: '/messages'
      fullPath: '/app/advertiser/messages'
      preLoaderRoute: typeof AppAdvertiserMessagesRouteImport
      parentRoute: typeof AppAdvertiserRoute
    }
    '/app/advertiser/discover': {
      id: '/app/advertiser/discover'
      path: '/discover'
      fullPath: '/app/advertiser/discover'
      preLoaderRoute: typeof AppAdvertiserDiscoverRouteImport
      parentRoute: typeof AppAdvertiserRoute
    }
    '/app/advertiser/campaigns': {
      id: '/app/advertiser/campaigns'
      path: '/campaigns'
      fullPath: '/app/advertiser/campaigns'
      preLoaderRoute: typeof AppAdvertiserCampaignsRouteImport
      parentRoute: typeof AppAdvertiserRoute
    }
    '/app/advertiser/bookings': {
      id: '/app/advertiser/bookings'
      path: '/bookings'
      fullPath: '/app/advertiser/bookings'
      preLoaderRoute: typeof AppAdvertiserBookingsRouteImport
      parentRoute: typeof AppAdvertiserRoute
    }
    '/app/advertiser/billing': {
      id: '/app/advertiser/billing'
      path: '/billing'
      fullPath: '/app/advertiser/billing'
      preLoaderRoute: typeof AppAdvertiserBillingRouteImport
      parentRoute: typeof AppAdvertiserRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/reports': {
      id: '/app/admin/reports'
      path: '/reports'
      fullPath: '/app/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/providers': {
      id: '/app/admin/providers'
      path: '/providers'
      fullPath: '/app/admin/providers'
      preLoaderRoute: typeof AppAdminProvidersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/lookups': {
      id: '/app/admin/lookups'
      path: '/lookups'
      fullPath: '/app/admin/lookups'
      preLoaderRoute: typeof AppAdminLookupsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/finance': {
      id: '/app/admin/finance'
      path: '/finance'
      fullPath: '/app/admin/finance'
      preLoaderRoute: typeof AppAdminFinanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/campaigns': {
      id: '/app/admin/campaigns'
      path: '/campaigns'
      fullPath: '/app/admin/campaigns'
      preLoaderRoute: typeof AppAdminCampaignsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/advertiser/discover/$id': {
      id: '/app/advertiser/discover/$id'
      path: '/$id'
      fullPath: '/app/advertiser/discover/$id'
      preLoaderRoute: typeof AppAdvertiserDiscoverIdRouteImport
      parentRoute: typeof AppAdvertiserDiscoverRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCampaignsRoute: typeof AppAdminCampaignsRoute
  AppAdminFinanceRoute: typeof AppAdminFinanceRoute
  AppAdminLookupsRoute: typeof AppAdminLookupsRoute
  AppAdminProvidersRoute: typeof AppAdminProvidersRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCampaignsRoute: AppAdminCampaignsRoute,
  AppAdminFinanceRoute: AppAdminFinanceRoute,
  AppAdminLookupsRoute: AppAdminLookupsRoute,
  AppAdminProvidersRoute: AppAdminProvidersRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAdvertiserDiscoverRouteChildren {
  AppAdvertiserDiscoverIdRoute: typeof AppAdvertiserDiscoverIdRoute
}

const AppAdvertiserDiscoverRouteChildren: AppAdvertiserDiscoverRouteChildren = {
  AppAdvertiserDiscoverIdRoute: AppAdvertiserDiscoverIdRoute,
}

const AppAdvertiserDiscoverRouteWithChildren =
  AppAdvertiserDiscoverRoute._addFileChildren(
    AppAdvertiserDiscoverRouteChildren,
  )

interface AppAdvertiserRouteChildren {
  AppAdvertiserBillingRoute: typeof AppAdvertiserBillingRoute
  AppAdvertiserBookingsRoute: typeof AppAdvertiserBookingsRoute
  AppAdvertiserCampaignsRoute: typeof AppAdvertiserCampaignsRoute
  AppAdvertiserDiscoverRoute: typeof AppAdvertiserDiscoverRouteWithChildren
  AppAdvertiserMessagesRoute: typeof AppAdvertiserMessagesRoute
  AppAdvertiserProfileRoute: typeof AppAdvertiserProfileRoute
  AppAdvertiserReviewsRoute: typeof AppAdvertiserReviewsRoute
  AppAdvertiserIndexRoute: typeof AppAdvertiserIndexRoute
}

const AppAdvertiserRouteChildren: AppAdvertiserRouteChildren = {
  AppAdvertiserBillingRoute: AppAdvertiserBillingRoute,
  AppAdvertiserBookingsRoute: AppAdvertiserBookingsRoute,
  AppAdvertiserCampaignsRoute: AppAdvertiserCampaignsRoute,
  AppAdvertiserDiscoverRoute: AppAdvertiserDiscoverRouteWithChildren,
  AppAdvertiserMessagesRoute: AppAdvertiserMessagesRoute,
  AppAdvertiserProfileRoute: AppAdvertiserProfileRoute,
  AppAdvertiserReviewsRoute: AppAdvertiserReviewsRoute,
  AppAdvertiserIndexRoute: AppAdvertiserIndexRoute,
}

const AppAdvertiserRouteWithChildren = AppAdvertiserRoute._addFileChildren(
  AppAdvertiserRouteChildren,
)

interface AppProviderRouteChildren {
  AppProviderBookingsRoute: typeof AppProviderBookingsRoute
  AppProviderFinancesRoute: typeof AppProviderFinancesRoute
  AppProviderInventoryRoute: typeof AppProviderInventoryRoute
  AppProviderMessagesRoute: typeof AppProviderMessagesRoute
  AppProviderProfileRoute: typeof AppProviderProfileRoute
  AppProviderRequestsRoute: typeof AppProviderRequestsRoute
  AppProviderReviewsRoute: typeof AppProviderReviewsRoute
  AppProviderIndexRoute: typeof AppProviderIndexRoute
}

const AppProviderRouteChildren: AppProviderRouteChildren = {
  AppProviderBookingsRoute: AppProviderBookingsRoute,
  AppProviderFinancesRoute: AppProviderFinancesRoute,
  AppProviderInventoryRoute: AppProviderInventoryRoute,
  AppProviderMessagesRoute: AppProviderMessagesRoute,
  AppProviderProfileRoute: AppProviderProfileRoute,
  AppProviderRequestsRoute: AppProviderRequestsRoute,
  AppProviderReviewsRoute: AppProviderReviewsRoute,
  AppProviderIndexRoute: AppProviderIndexRoute,
}

const AppProviderRouteWithChildren = AppProviderRoute._addFileChildren(
  AppProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  InfluencersRoute: InfluencersRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAdvertiserRoute: AppAdvertiserRouteWithChildren,
  AppProviderRoute: AppProviderRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthSignupRoute: AuthSignupRoute,
  OnboardingAdvertiserRoute: OnboardingAdvertiserRoute,
  OnboardingProviderRoute: OnboardingProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
